version: '3.5'

services:
  web_server:
    container_name: twnpx-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app

  app:
    container_name: twnpx-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: database.conf
    expose:
      - 8080
    depends_on:
      - database

  database:
    container_name: twnpx-postgres
    image: postgres:alpine
    env_file: database.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: